kutuphane_otomasyonu/kutuphane_otomasyonu/Controllers/KitapTurleriController.cs
using Microsoft.Ajax.Utilities;
using MVC_kutuphane_otomasyonu_entities.DataAccessLayer;
using MVC_kutuphane_otomasyonu_entities.Model;
using MVC_kutuphane_otomasyonu_entities.Model.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kutuphane_otomasyonu.Controllers
{
    [AllowAnonymous]

    public class KitapTurleriController : Controller
    {
        // GET: KitapTurleri
        KutuphaneContext context = new KutuphaneContext();
        KitapTurleriDAL KitapTurleriDAL = new KitapTurleriDAL();
        public ActionResult Index2(string ara,int ? page)
        {
            var model = KitapTurleriDAL.GetAll(context).ToPagedList(page ?? 1,3);
            if (ara != null)
            {
                model = KitapTurleriDAL.GetAll(context,x=>x.KitapTuru.Contains(ara)).ToPagedList(page ?? 1, 3);
            }
            return View("Index",model);
        }
        // bu kisim get icin kullanilir.
        public ActionResult Ekle()
        {
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]


        // bu kisim post islmei icin kullanilir ve dogrulama islemi yapilir. 
        public ActionResult Ekle(KitapTurleri kitapTurleri)
        {
            if (ModelState.IsValid)//model dogrulanirsa bu islemi gerceklestir
            {
                KitapTurleriDAL.InsertUpdate(context, kitapTurleri);
                KitapTurleriDAL.Save(context);
                return RedirectToAction("Index");//listelemededn sonra index sayfasina yonlendirecek.
            }
            return View(kitapTurleri);//model dogrulanmazas islem gerceklestirilmez
        }
       //burasi http get kismi icin 
        public ActionResult Duzenle(int? id)
        {
            if (id==null)
            {
                return HttpNotFound();
            }
            var model=KitapTurleriDAL.GetById(context, id); 
            return View(model); 
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Duzenle(KitapTurleri kitapTurleri)
        {
            if (ModelState.IsValid)//model dogrulanirsa bu islemi gerceklestir
            {
                KitapTurleriDAL.InsertUpdate(context, kitapTurleri);
                KitapTurleriDAL.Save(context);
                return RedirectToAction("Index");//listelemededn sonra index sayfasina yonlendirecek.
            }
            return View(kitapTurleri);
        }
        public ActionResult Sil(int? id)
        {
            KitapTurleriDAL.Delete(context,x=>x.Id==id);
            KitapTurleriDAL.Save(context);
            return RedirectToAction("Index");
        }
    }
}

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/KitapTurleri/Duzenle.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.KitapTurleri
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">

    <div class="col-lg">
        <div class="ibox">
            <div class="ibox ibox-head">
                Kitap Turu Guncelleme Sayfasi
            </div>

            <div class="ibox-body">


                @using (Html.BeginForm("Duzenle", "KitapTurleri", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    @Html.HiddenFor(x => x.Id)

                    <div class="form-group">
                        <div>
                            @Html.LabelFor(x => x.KitapTuru)
                        </div>
                        <div>
                            @Html.TextBoxFor(x => x.KitapTuru, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.KitapTuru, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            @Html.LabelFor(x => x.Aciklama)
                        </div>
                        <div>
                            @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                      <input type="submit" value="Duzenle" class="btn btn-warning" /> 

                    </div>


                }

            </div>






        </div>
    </div>


</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/KitapTurleri/Ekle.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.KitapTurleri
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">

    <div class="col-lg">
        <div class="ibox">
            <div class="ibox ibox-head">
                Kitap Turu Ekleme Sayfasi 
            </div>

            <div class="ibox-body">
                <form action="Ekle" method="post">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    <div class="form-group">
                        Kitap Turu :
                        <input type="text" name="KitapTuru" class=" form-control" />
                        @Html.ValidationMessageFor(x => x.KitapTuru, "", new {@class="text-danger"})
                    </div>
                    <div class="form-group">
                        Aciklama:
                        <textarea name="Aciklama" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ekle" class="btn btn-success">

                    </div>
                </form>

            </div>






        </div>
    </div>


</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/KitapTurleri/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_kutuphane_otomasyonu_entities.Model.KitapTurleri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@*//namein parametre ile ayni isimde olmasi gerekiyor.*@
<form action="Index2">
    <label style="font-weight:bold">Kitap Turu Ara :</label>
    @Html.TextBox("ara")
    <button type="submit">Ara</button>
</form>

<div class="row">

    <div class="col-lg">
        <div class="ibox">
            <div class="ibox ibox-head">
                Kitap Turleri Listesi
            </div>

            <div class="ibox-body">
                <table class=" table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Kitap Turu</th>
                            <th>Aciklama</th>
                            <th>Duzenle</th>
                            <th>Sil</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@item.Id</th>
                                <th>@item.KitapTuru</th>
                                <th>@item.Aciklama</th>
                                <th><a href="/KitapTurleri/Duzenle/@item.Id" class="btn btn-warning">Duzenle</a></th>
                                <th><a href="/KitapTurleri/Sil/@item.Id" class="btn btn-danger">Sil</a></th>

                            </tr>

                        }
                    </tbody>

                </table>
                @Html.PagedListPager(Model,page =>Url.Action("Index","KitapTurleri",new { page, ara = Request.QueryString["ara"] }),new PagedListRenderOptions
           {
               FunctionToTransformEachPageLink = (li, a) =>
               {
                   a.AddCssClass("page-link");
                   li.InnerHtml = a.ToString();
                   return li;
               }
           })





                <a href="/KitapTurleri/Ekle" class="btn btn-success">Yeni</a>

            </div>






        </div>
    </div>


</div>