kutuphane_otomasyonu/kutuphane_otomasyonu/Controllers/KitaplarController.cs
using MVC_kutuphane_otomasyonu_entities.DataAccessLayer;
using MVC_kutuphane_otomasyonu_entities.Model.Context;
using MVC_kutuphane_otomasyonu_entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_kutuphane_otomasyonu_entities.Model;

namespace kutuphane_otomasyonu.Controllers
{
    [Authorize(Roles = "Admin")]
    public class KitaplarController : Controller
    {
        // GET: Kitaplar
        KutuphaneContext context = new KutuphaneContext();
        KitaplarDAL KitaplarDAL = new KitaplarDAL();
        KitapKayitHareketleriDAL kitapKayitHareketleriDAL = new KitapKayitHareketleriDAL();
        KullanicilarDAL kullanicilarDAL = new KullanicilarDAL();

        public void KitapKayitHareketleri(int kullaniciId, int kitapId, string YapilanIslem, string aciklama)
        {
            var model = new KitapKayitHareketleri
            {
                Aciklama = aciklama,
                KullaniciId = kullaniciId,
                KitapId = kitapId,
                YapilanIslem = YapilanIslem,
                Tarih = DateTime.Now,
            };
            kitapKayitHareketleriDAL.InsertUpdate(context, model);
            kitapKayitHareketleriDAL.Save(context);
        }





        public ActionResult Index(KitaplarDAL KitaplarDAL)
        {
            var model = KitaplarDAL.GetAll(context, null, "KitapTurleri");
            return View(model);
        }
        public ActionResult Ekle()
        {
            ViewBag.liste = new SelectList(context.kitapTurleris, "Id", "KitapTuru");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ekle(Kitaplar entity)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.liste = new SelectList(context.kitapTurleris, "Id", "KitapTuru");
                return View(entity);
            }
            KitaplarDAL.InsertUpdate(context, entity);
            KitaplarDAL.Save(context);

            int kitapId = context.kitaplars.Max(x => x.Id);
            var userName = User.Identity.Name;
            var modelKullanici = kullanicilarDAL.GetByFilter(context, x => x.Email == userName);
            int kullaniciId = modelKullanici.Id;
            KitapKayitHareketleri(kullaniciId, kitapId, modelKullanici.KullaniciAdi + " kullanicisi yeni bir kitap ekledi.", " Kitap ekleme isi");



            return RedirectToAction("Index");
        }
        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            ViewBag.liste = new SelectList(context.kitapTurleris, "Id", "KitapTuru");
            var model = KitaplarDAL.GetByFilter(context, x => x.Id == id, "KitapTurleri");
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle(Kitaplar entity)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.liste = new SelectList(context.kitapTurleris, "Id", "KitapTuru");
                return View(entity);
            }
            KitaplarDAL.InsertUpdate(context, entity);
            KitaplarDAL.Save(context);

            int kitapId = entity.Id;
            var userName = User.Identity.Name;
            var modelKullanici = kullanicilarDAL.GetByFilter(context, x => x.Email == userName);
            int kullaniciId = modelKullanici.Id;
            KitapKayitHareketleri(kullaniciId, kitapId, modelKullanici.KullaniciAdi + " kullanicisi kitap uzerinde degisiklik gerceklestirdi.", " Kitap duzeltme islemi.");



            return RedirectToAction("Index");
        }
        public ActionResult Detay(int? id)
        {
            var model = KitaplarDAL.GetByFilter(context, x => x.Id == id, "KitapTurleri");
            return View(model);
        }
        public ActionResult Sil(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            KitaplarDAL.Delete(context, x => x.Id == id);
            KitaplarDAL.Save(context);
            return RedirectToAction("Index");
        }
    }
}

kutuphane_otomasyonu/kutuphane_otomasyonu/Controllers/KullanicilarController.cs
using MVC_kutuphane_otomasyonu_entities.DataAccessLayer;
using MVC_kutuphane_otomasyonu_entities.Model;
using MVC_kutuphane_otomasyonu_entities.Model.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MVC_kutuphane_otomasyonu_entities.Model.ViewModel;

namespace kutuphane_otomasyonu.Controllers
{

    //[AllowAnonymous]   // calismazsa bu kismin yorum sarini kaldir.
    [Authorize(Roles = "Admin,Moderator")] // global tarafindaki kismi burada insanlarin girebilecegi hlae getiriyorum.
    public class KullanicilarController : Controller
    {
        // GET: Kullanicilar
        KutuphaneContext context = new KutuphaneContext();
        KullanicilarDAL kullanicilarDAL = new KullanicilarDAL();
        KullaniciRolleriDAL KullaniciRolleriDAL = new KullaniciRolleriDAL();
        RollerDAL rollerDal = new RollerDAL();
        KullaniciHareketleriDAL kullaniciHareketleriDAL = new KullaniciHareketleriDAL();

        public void KullaniciHareketleri(int kullaniciId, int islenYapanId, string aciklama)
        {
            var model = new KullaniciHareketleri
            {
                Aciklama = aciklama,
                IslemYapan = islenYapanId,
                KullaniciId = kullaniciId,
                Tarih = DateTime.Now,
            };
            kullaniciHareketleriDAL.InsertUpdate(context, model);
            kullaniciHareketleriDAL.Save(context);
        }
        public ActionResult Index()
        {
            var model = kullanicilarDAL.GetAll(context);
            return View(model);
        }

        public ActionResult Ekle()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Ekle(Kullanicilar entity)
        {
            if (!ModelState.IsValid)
            {
                return View(entity);
            }
            kullanicilarDAL.InsertUpdate(context, entity);
            kullanicilarDAL.Save(context);

            int kullaniciId = context.Kullanicilars.Max(x => x.Id);
            var userName = User.Identity.Name;
            var model = kullanicilarDAL.GetByFilter(context, x => x.Email == userName);
            var islemYapanId = model.Id;
            string aciklama = model.KullaniciAdi + "kullanici yeni bir kullanici ekledi";


            KullaniciHareketleri(kullaniciId, islemYapanId, aciklama);


            return RedirectToAction("Index2");
        }

        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return HttpNotFound("id degeri girilmedi.");
            }

            var model = kullanicilarDAL.GetById(context, id);
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Duzenle(Kullanicilar entity)
        {
            if (!ModelState.IsValid)
            {
                return View(entity);
            }
            kullanicilarDAL.InsertUpdate(context, entity);
            kullanicilarDAL.Save(context);
            return RedirectToAction("Index2");
        }


        public ActionResult Index2()
        {
            var kullanicilar = kullanicilarDAL.GetAll(context, tbl: "KullaniciRolleri");
            var roller = rollerDal.GetAll(context);
            return View(new KullaniciRolViewModel { Kullanicilar = kullanicilar, Roller = roller });
        }

        public ActionResult KRolleri(int id)
        {
            var model = KullaniciRolleriDAL.GetAll(context, x => x.KullaniciId == id, "Roller");
            if (model != null)
            {
                return View(model);
            }
            return HttpNotFound();
        }


        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(Kullanicilar entity)
        {
            if (User.Identity.IsAuthenticated)
            {
                FormsAuthentication.SignOut();
            }

            var model = kullanicilarDAL.GetByFilter(context, x => x.Email == entity.Email && x.Sifre == entity.Sifre);
            if (model != null)// burasi == di != yapinca giris yapti 
            {
                FormsAuthentication.SetAuthCookie(entity.Email, false);



                int islemYapanId = model.Id;
                string aciklama = model.KullaniciAdi + "kullanici sisteme giris yapti.";

                KullaniciHareketleri(islemYapanId, islemYapanId, aciklama);





                return RedirectToAction("Index2", "KitapTurleri");/*burasi hata veirse index dize duzlet*/
            }
            ViewBag.error = "Kullanici adi veya sifre yanlis.";
            return View();
        }

        [AllowAnonymous]
        public ActionResult KayitOl()
        {

            return View();
        }
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult KayitOl(Kullanicilar entity, string sifreTekrar, bool kabul)
        {

            if (!ModelState.IsValid) //Model dogrulanmazsa
            {
                return View(entity);
            }
            else//Model Dogrulanirsa
            {
                if (entity.Sifre != sifreTekrar)//sifreler uyusmazsa
                {
                    ViewBag.sifreError = "Sifreler uyusmuyor.";
                    return View();
                }
                else//sifreler uyusursa
                {
                    if (!kabul)// sartlar kabul edilmemisse
                    {
                        ViewBag.kabulError = "Lutfen Sartlari Kabul Ettiniginizi Onaylayiniz!";
                        return View();
                    }
                    else//sartlar kabul edilmisse 
                    {
                        entity.KayitTarihi = DateTime.Now;
                        kullanicilarDAL.InsertUpdate(context, entity);
                        kullanicilarDAL.Save(context);

                        int kullaniciId = context.Kullanicilars.Max(x => x.Id);


                        string aciklama = "Yeni bir kullanici olusturuldu.";


                        KullaniciHareketleri(kullaniciId, kullaniciId, aciklama);
                        return RedirectToAction("Login");
                    }
                }
            }
        }
        [AllowAnonymous]

        public ActionResult SifremiUnuttum()
        {
            return View();
        }

        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SifremiUnuttum(Kullanicilar entity)
        {
            var model = kullanicilarDAL.GetByFilter(context, x => x.Email == entity.Email);

            if (model != null)
            {
                // Yeni rastgele şifre oluştur
                Guid rastgele = Guid.NewGuid();
                model.Sifre = rastgele.ToString().Substring(0, 8);
                kullanicilarDAL.Save(context);

                try
                {
                    SmtpClient client = new SmtpClient("smtp.outlook.com", 587);
                    client.EnableSsl = true;

                    MailMessage mail = new MailMessage();
                    mail.From = new MailAddress("muratakay123456@hotmail.com", "Kutuphane Sistemi");
                    mail.To.Add(model.Email);
                    mail.IsBodyHtml = true;
                    mail.Subject = "Şifre Değiştirme İsteği";
                    mail.Body += "Merhaba " + model.AdiSoyadi + "<br/>Kullanıcı Adınız: " + model.KullaniciAdi + "<br/>Yeni Şifreniz: " + model.Sifre;

                    // *** Gerçek şifre yerine uygulama parolası kullan ***
                    NetworkCredential net = new NetworkCredential("muratakay123456@hotmail.com", "UYGULAMA_PAROLASI_BURAYA");
                    client.Credentials = net;

                    client.Send(mail);

                    ViewBag.Success = "Yeni şifreniz e-posta adresinize gönderildi.";
                }
                catch (Exception ex)
                {
                    ViewBag.hata = "Mail gönderilirken bir hata oluştu: " + ex.Message;
                    return View();
                }
            }
            else if (entity.Email != null)
            {
                ViewBag.hata = "Böyle bir e-posta adresi bulunamadı.";
                return View();
            }

            return View();
        }

    }
}

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Kullanicilar/Duzenle.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.Kullanicilar
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                @*//<h2 class="login-title">Kullanici Duzenleme Islemleri</h2>*@
            </div>
            <div class="ibox-body">
                @using (Html.BeginForm("Duzenle", "Kullanicilar", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "Duzenle", new { @class = "text-danger" })

                    <h2 class="login-title">Kullanici Duzenleme Islemleri</h2>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control", placeholder = "Adi Soyadi" })
                        @Html.ValidationMessageFor(x => x.AdiSoyadi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control", placeholder = "Telefon" })
                        @Html.ValidationMessageFor(x => x.Telefon, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(x => x.Adres, new { @class = "form-control", placeholder = "Adres" })
                        @Html.ValidationMessageFor(x => x.Adres, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "E-mail" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.KullaniciAdi, new { @class = "form-control", placeholder = "Kullanici Adi" })
                        @Html.ValidationMessageFor(x => x.KullaniciAdi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control", placeholder = "Sifre" })
                        @Html.ValidationMessageFor(x => x.Sifre, "", new { @class = "text-danger" })
                    </div>
                    @*<div class="form-group">
                        *Html.DisplayNameFor(x => x.KayitTarihi)
                        @Html.TextBoxFor(x => x.KayitTarihi, new { @class = "form-control", type = "datetime-local",Value=Model.KayitTarihi.ToString("yyyy-MM-dd HH:mm") })
                        @Html.ValidationMessageFor(x => x.KayitTarihi, "", new { @class = "text-danger" })
                    </div>*@

                    <div class="form-group">
                        <button class="btn btn-primary " type="submit">Kaydet</button>
                    </div>

                }

            </div>

        </div>

    </div>



</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Kullanicilar/Ekle.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.Kullanicilar
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                @*//<h2 class="login-title">Kullanici Ekleme Islemleri</h2>*@
            </div>
            <div class="ibox-body">
                @using (Html.BeginForm("Ekle", "Kullanicilar", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <h2 class="login-title">Kullanici Ekleme Islemleri</h2>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control", placeholder = "Adi Soyadi" })
                        @Html.ValidationMessageFor(x => x.AdiSoyadi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control", placeholder = "Telefon" })
                        @Html.ValidationMessageFor(x => x.Telefon, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(x => x.Adres, new { @class = "form-control", placeholder = "Adres" })
                        @Html.ValidationMessageFor(x => x.Adres, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "E-mail" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x.KullaniciAdi, new { @class = "form-control", placeholder = "Kullanici Adi" })
                        @Html.ValidationMessageFor(x => x.KullaniciAdi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.PasswordFor(x => x.Sifre, new { @class = "form-control", placeholder = "Sifre" })
                        @Html.ValidationMessageFor(x => x.Sifre, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.KayitTarihi)
                        @Html.TextBoxFor(x => x.KayitTarihi, new { @class = "form-control", type = "datetime-local" })
                        @Html.ValidationMessageFor(x => x.KayitTarihi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <button class="btn btn-info " type="submit">Ekle</button>
                    </div>

                }

            </div>

        </div>

    </div>



</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Kullanicilar/Index.cshtml
@model List<MVC_kutuphane_otomasyonu_entities.Model.Kullanicilar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Kullanıcı Listesi
            </div>
            <div class="ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Kullanıcı Adı</th>
                            <th>Adı Soyadı</th>
                            <th>Telefon</th>
                            <th>E-mail</th>
                            <th>Kayıt Tarihi</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(x => item.Id)</td>
                                <td>@Html.DisplayFor(x => item.KullaniciAdi)</td>
                                <td>@Html.DisplayFor(x => item.AdiSoyadi)</td>
                                <td>@Html.DisplayFor(x => item.Telefon)</td>
                                <td>@Html.DisplayFor(x => item.Email)</td>
                                <td>@Html.DisplayFor(x => item.KayitTarihi)</td>
                                <td>
                                    @Html.ActionLink("Düzenle", "Duzenle", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" }) |
                                    @Html.ActionLink("Detay", "Detay", new { id = item.Id }, new { @class = "btn btn-info btn-sm" }) |
                                    @Html.ActionLink("Sil", "Sil", "Kullanicilar", new { id = item.Id }, new { @class = "btn btn-danger btn-sm delete", onclick = "return confirm('Kayıt silinsin mi?')" }) |
                                    @Html.ActionLink("Rolleri", "KRolleri", "Kitaplar", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="form-group">
                    @Html.ActionLink("Yeni Kullanıcı Ekle", "Ekle", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    </div>
</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Kullanicilar/Index2.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.ViewModel.KullaniciRolViewModel

@{
    ViewBag.Title = "Kullanıcı Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                <h3>Kullanıcı Listesi</h3>
            </div>
            <div class="ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Kullanıcı Adı</th>
                            <th>Adı Soyadı</th>
                            <th>Roller</th>
                            <th>Telefon</th>
                            <th>E-mail</th>
                            <th>Kayıt Tarihi</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var kullanici in Model.Kullanicilar)
                        {
                            <tr>
                                <td>@Html.DisplayFor(x => kullanici.Id)</td>
                                <td>@Html.DisplayFor(x => kullanici.KullaniciAdi)</td>
                                <td>@Html.DisplayFor(x => kullanici.AdiSoyadi)</td>
                                <td>
                                    <ul class="list-unstyled mb-2">
                                        @foreach (var rol in kullanici.KullaniciRolleri)
                                        {
                                            <li class="mb-2 d-flex justify-content-between align-items-center">
                                                <span>@rol.Roller.Rol</span>
                                                <span>
                                                    @Html.ActionLink("Düzenle", "Duzenle", "KullaniciRolleri", new { id = rol.Id }, new { @class = "btn btn-warning btn-sm me-1" })
                                                    @Html.ActionLink("Sil", "Sil", "KullaniciRolleri", new { id = rol.Id }, new { @class = "btn btn-danger btn-sm delete", onclick = "return confirm('Kayıt silinsin mi?')" })
                                                </span>
                                            </li>
                                        }
                                    </ul>
                                    @Html.ActionLink("Yeni Rol Ekle", "Ekle", "KullaniciRolleri", new { id = kullanici.Id }, new { @class = "btn btn-success btn-sm mt-2" })
                                </td>
                                <td>@Html.DisplayFor(x => kullanici.Telefon)</td>
                                <td>@Html.DisplayFor(x => kullanici.Email)</td>
                                <td>@Html.DisplayFor(x => kullanici.KayitTarihi)</td>
                                <td>
                                    @Html.ActionLink("Düzenle", "Duzenle", new { id = kullanici.Id }, new { @class = "btn btn-warning btn-sm me-1" })
                                    @Html.ActionLink("Sil", "Sil", "Kullanicilar", new { id = kullanici.Id }, new { @class = "btn btn-danger btn-sm delete", onclick = "return confirm('Kayıt silinsin mi?')" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="form-group mt-3">
                    @Html.ActionLink("Yeni Kullanıcı Ekle", "Ekle", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Stil ve script -->
<link href="~/style.css" rel="stylesheet" />
<script src="~/JavaScript.js"></script>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Kullanicilar/KRolleri.cshtml
@model List<MVC_kutuphane_otomasyonu_entities.Model.KullaniciRolleri> /* BURADA HATA OABILIR.*/
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Kullanici Rolleri Listesi
            </div>
            <div class=" ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Kullanici</th>
                            <th>Rol</th>
                          
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>
                                    @Html.DisplayFor(x => item.Id)
                                </th>
                                <td> @Html.DisplayFor(x => item.Id)</td>
                                <td> @Html.DisplayFor(x => item.KullaniciId)</td>
                                <td> @Html.DisplayFor(x => item.Roller.Rol)</td>
                                <td>
                                    @Html.ActionLink("Edit", "Duzenle", "Roller", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                                    @Html.ActionLink("Detay", "Detay", "Roller", new { id = item.Id }, new { @class = "btn btn-info btn-sm" }) |
                                    @Html.ActionLink("Sil", "Sil", "Roller", new { id = item.Id }, new { @class = "btn btn-danger btn-sm delete", onclick = "return confirm('kayit silinsin mi ?')" })
                                   
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
                <div class="form-group">
                    @Html.ActionLink("Yeni", null, "Ekle", "Roller", new { @class = "btn btn-succes" })
                </div>

            </div>

        </div>

    </div>

</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Kullanicilar/SifremiUnuttum.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.Kullanicilar
@{
    ViewBag.Title = "SifremiUnuttum";
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title>Admincast bootstrap 4 &amp; MVC Kutuphane Otomasyonu | Sifremi Unuttum</title>
    <!-- GLOBAL MAINLY STYLES-->
    <link href="~/AdminDasboard/admincast-master/html/dist/assets/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- THEME STYLES-->
    <link href="~/AdminDasboard/admincast-master/html/dist/assets/css/main.css" rel="stylesheet" />
    <!-- PAGE LEVEL STYLES-->
    <link href="~/AdminDasboard/admincast-master/html/dist/assets/css/pages/auth-light.css" rel="stylesheet" />
</head>

<body class="bg-silver-300">
    <div class="content">
        <div class="brand">
            <a class="link" href="/Kitaplar/Index" style="font-size:large">MVC Kutuphane Otomasyonu</a>
        </div>

        @using (Html.BeginForm("SifremiUnuttum", "Kullanicilar", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
          

            <h3 class="m-t-10 m-b-10">Şifremi Unuttum</h3>
            <p class="m-b-20">İşlem sonunda mail adresinize yeni şifreniz gönderilecek.</p>
            <div class="form-group">
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "E-mail", required = "required", type = "email" })
                @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
            </div>

            <div>
                @if (ViewBag.hata != null)
                {
                    <div class="alert alert-danger">@ViewBag.hata</div>
                }
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success">@ViewBag.Success</div>
                }
            </div>
            <div class="form-group">
                <button class="btn btn-info btn-block" type="submit">Gönder</button>
            </div>
        }
    </div>
    <!-- BEGIN PAGA BACKDROPS-->
    <div class="sidenav-backdrop backdrop"></div>
    <div class="preloader-backdrop">
        <div class="page-preloader">Loading</div>
    </div>
    <!-- END PAGA BACKDROPS-->
    <!-- CORE PLUGINS -->
    <script src="~/AdminDasboard/admincast-master/html/dist/assets/vendors/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/AdminDasboard/admincast-master/html/dist/assets/vendors/popper.js/dist/umd/popper.min.js" type="text/javascript"></script>
    <script src="~/AdminDasboard/admincast-master/html/dist/assets/vendors/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- PAGE LEVEL PLUGINS -->
    <script src="~/AdminDasboard/admincast-master/html/dist/assets/vendors/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <!-- CORE SCRIPTS-->
    <script src="~/AdminDasboard/admincast-master/html/dist/assets/js/app.js" type="text/javascript"></script>
    <!-- PAGE LEVEL SCRIPTS-->
</body>
</html>