kutuphane_otomasyonu/kutuphane_otomasyonu/Controllers/UyelerController.cs
using MVC_kutuphane_otomasyonu_entities.DataAccessLayer;
using MVC_kutuphane_otomasyonu_entities.Model;
using MVC_kutuphane_otomasyonu_entities.Model.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kutuphane_otomasyonu.Controllers
{
    [AllowAnonymous]
    public class UyelerController : Controller
    {
        // GET: Uyeler
        KutuphaneContext context = new KutuphaneContext();
        UyelerDAL uyelerDAL = new UyelerDAL();
        public ActionResult Index()
        {
            var model = uyelerDAL.GetAll(context);
            return View(model); // Bu şekilde model gönderilmeli
        }


        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Ekle(Uyeler entity, HttpPostedFileBase ResimYolu)
        {
            if (ModelState.IsValid)
            {
                if (ResimYolu != null && ResimYolu.ContentLength > 0)
                {
                    var image = Path.GetFileName(ResimYolu.FileName);
                    string path = Path.Combine(Server.MapPath("~/images"), image);
                    if (System.IO.File.Exists(path) == false)
                    {
                        ResimYolu.SaveAs(path);
                    }
                    entity.ResimYolu = "/images/" + image;

                }
                uyelerDAL.InsertUpdate(context, entity);
                uyelerDAL.Save(context);
                return RedirectToAction("Index");

            }
            return View(entity);
        }

        public ActionResult Duzenle(int? id)
        {

            if (id == null)
            {
                return HttpNotFound();
            }
            var model = uyelerDAL.GetByFilter(context, x => x.Id == id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Duzenle(Uyeler entity, HttpPostedFileBase ResimYolu)
        {
            if (ModelState.IsValid)
            {
                var model = uyelerDAL.GetByFilter(context, x => x.Id == entity.Id);
                entity.ResimYolu = model.ResimYolu;
                if (ResimYolu != null && ResimYolu.ContentLength > 0)
                {
                    var image = Path.GetFileName(ResimYolu.FileName);
                    string path = Path.Combine(Server.MapPath("~/images"), image);
                    if (System.IO.File.Exists(path) == false)
                    {
                        ResimYolu.SaveAs(path);
                    }
                    entity.ResimYolu = "/images/" + image;

                }
                uyelerDAL.InsertUpdate(context, entity);
                uyelerDAL.Save(context);
                return RedirectToAction("Index");

            }
            return View(entity);
        }

        public ActionResult Sil(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            uyelerDAL.Delete(context,x=>x.Id == id);
            uyelerDAL.Save(context);
            return RedirectToAction("Index");
        }
    }
}

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Uyeler/Duzenle.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.Uyeler

@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">

    <div class="col-lg">
        <div class="ibox">
            <div class="ibox ibox-head">
                Uye Duzenleme Sayfasi
            </div>

            <div class="ibox-body">
                @using (Html.BeginForm("Duzenle", "Uyeler", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <img src="@Model.ResimYolu" width="100" height="100" />
                    </div>

                    <div class="form-group">
                        @Html.Label("Yeni Resim Yükle")
                        <input type="file" name="ResimYolu" class="form-control" />
                    </div>


                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.AdiSoyadi)
                        @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.AdiSoyadi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.Telefon)
                        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Telefon, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.Adres)
                        @Html.TextBoxFor(x => x.Adres, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Adres, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.Email)
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>



                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.OkulKitapSayisi)
                        @Html.TextBoxFor(x => x.OkulKitapSayisi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.OkulKitapSayisi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Ekle</button>

                    </div>

                }

            </div>
        </div>
    </div>
</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Uyeler/Ekle.cshtml
@model MVC_kutuphane_otomasyonu_entities.Model.Uyeler

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">

    <div class="col-lg">
        <div class="ibox">
            <div class="ibox ibox-head">
                Uye Ekleme Sayfasi
            </div>

            <div class="ibox-body">
                @using (Html.BeginForm("Ekle", "Uyeler", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.AdiSoyadi)
                        @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.AdiSoyadi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.Telefon)
                        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Telefon, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.Adres)
                        @Html.TextBoxFor(x => x.Adres, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Adres, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.Email)
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.ResimYolu)
                        @Html.TextBoxFor(x => x.ResimYolu, new { @class = "form-control", type = "file" })

                    </div>

                    <div class="form-group">
                        @Html.DisplayNameFor(x => x.OkulKitapSayisi)
                        @Html.TextBoxFor(x => x.OkulKitapSayisi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.OkulKitapSayisi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Ekle</button>

                    </div>

                }

            </div>
        </div>
    </div>
</div>

kutuphane_otomasyonu/kutuphane_otomasyonu/Views/Uyeler/Index.cshtml
@model List<MVC_kutuphane_otomasyonu_entities.Model.Uyeler> /* BURADA HATA OABILIR.*/
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
               Uyeler
            </div>
            <div class=" ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Adi Soyadi</th>
                            <th>Telefon</th>
                            <th>Adresi</th>
                            <th>E-mail</th>
                            <th>Resim</th>
                            <th>Islemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>
                                    @Html.DisplayFor(x => item.Id)
                                </th>
                                <td> @Html.DisplayFor(x => item.AdiSoyadi)</td>
                                <td> @Html.DisplayFor(x => item.Telefon)</td>
                                <td> @Html.DisplayFor(x => item.Adres)</td>
                                <td> @Html.DisplayFor(x => item.Email)</td>
                                <td> <img src="@item.ResimYolu" width="100" height="100" /></td>
                                <td>
                                    @Html.ActionLink("Edit", "Duzenle", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                                    @Html.ActionLink("Sil", "Sil", new { id = item.Id }, new { @class = "btn btn-danger btn-sm delete", onclick = "return confirm('kayit silinsin mi ?')" })
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
                <div class="form-group">
                    @Html.ActionLink("Yeni", "Ekle", null, new { @class = "btn btn-success" })
                </div>


            </div>

        </div>

    </div>

</div>